# How to Use MACHINE LEARNING ALGORITHMS SUCH AS LINEAR REGRESSION TO MAKE BASIC PREDICTIONS

BY Muhammad Ammar Jamshed

In [42]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
dfh = pd.read_excel(r'C:\Users\muham\Downloads\Hour Price Prediction.csv.xlsx')

In [3]:
dfh.head()

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0   1          60     8450            7            5       2003          2003   
1   2          20     9600            6            8       1976          1976   
2   3          60    11250            7            5       2001          2002   
3   4          70     9550            7            5       1915          1970   
4   5          60    14260            8            5       2000          2000   

   BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  ...  WoodDeckSF  OpenPorchSF  \
0         706        150          856  ...           0           61   
1         978        284         1262  ...         298            0   
2         486        434          920  ...           0           42   
3         216        540          756  ...           0           35   
4         655        490         1145  ...         192           84   

   EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  \
0              0          0            0         0        0       2    2008   
1              0          0            0         0        0       5    2007   
2              0          0            0         0        0       9    2008   
3            272          0            0         0        0       2    2006   
4              0          0            0         0        0      12    2008   

   SalePrice  
0     208500  
1     181500  
2     223500  
3     140000  
4     250000  

[5 rows x 32 columns]

In [4]:
dfh.drop(['Id'],axis=1, inplace=True) # we use in place to drop the whole column

In [5]:
x = dfh.drop(['SalePrice'],axis=1)

In [6]:
y = dfh['SalePrice']

In [7]:
from sklearn.model_selection import train_test_split
# Seperate test and training data
Tx, Tex, Ty, Tey = train_test_split(x, y, test_size=0.4, random_state=0)

In [8]:
# import linear Regression 
from sklearn.linear_model import LinearRegression

In [9]:
ModelLR = LinearRegression()

In [10]:
ModelLR = ModelLR.fit(Tx, Ty)

In [11]:
ModelLR.intercept_

184357.84634249104

In [12]:
ModelLR.coef_

array([-1.60784695e+02,  4.50879380e-01,  1.78122314e+04,  4.20363560e+03,
        3.25161918e+02,  1.44932892e+02,  1.80923122e+01,  9.98391098e-01,
        2.29406190e+01,  1.42205536e+01,  2.14961866e+01,  3.32372726e+01,
        2.75407013e+03,  1.57027313e+03, -2.37363943e+02, -1.00743403e+04,
       -1.26704543e+04,  5.22927427e+03,  3.39930215e+03,  3.06737259e+02,
        3.03217598e+01,  2.35399859e+01,  3.05438878e+00, -8.39089102e+00,
        1.94959048e+01,  3.11462375e+01,  2.34550624e+01, -1.01344261e+00,
       -1.20541907e+02, -5.88299124e+02])

In [13]:
# Predict with test data only
ModelLR.predict(Tex)

array([ 2.55071670e+05,  1.56671932e+05,  9.80376116e+04,  2.27598979e+05,
        9.76393144e+04,  9.39747268e+04,  2.56847368e+05,  1.45457990e+05,
        5.14480587e+05,  1.47565429e+05,  1.86506441e+05,  1.52729576e+05,
        2.44934386e+05,  1.13751542e+05,  1.37557803e+05,  1.48243169e+05,
        2.36721083e+05,  1.01192491e+05,  1.33466118e+05,  1.79781439e+05,
        1.24086030e+05,  1.49399209e+05,  9.92316228e+04,  1.60191537e+05,
        1.94047155e+05,  1.99859838e+05,  1.49732532e+05,  4.06726568e+04,
        3.12612731e+05,  1.24881144e+05,  1.60295903e+05,  2.15479722e+05,
        1.54242559e+05,  2.86872693e+05,  2.91342791e+05,  2.02068821e+05,
        2.71953367e+05,  1.09934862e+05,  2.32246750e+05,  3.26869321e+05,
        2.15879338e+05,  1.14730181e+05,  1.94071373e+05,  2.92157105e+05,
        3.16544711e+05,  1.29845916e+05,  1.25797623e+05,  1.18456192e+05,
        1.85222382e+05,  8.12667549e+04,  3.66085281e+05,  1.46262217e+05,
        1.92601281e+05,  

In [14]:
prediction = ModelLR.predict(Tex)

In [15]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [16]:
r2_score(prediction, Tey)

0.7323156117279219

In [17]:
mean_absolute_error(prediction, Tey)

21315.384443599516

In [18]:
mean_squared_error(prediction, Tey)

1576006726.538537

In [19]:
# all errors have their intervals under which the values should ideally lie within 
# in order for the model to be reliable to apply on any business seting

In [20]:
# For logistic regression ML model

In [21]:
#same as Above with few changes

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

In [23]:
modelLogR = LinearRegression()

In [24]:
modelLogR.fit(Tx,Ty)

LinearRegression()

In [34]:
predictLinR = ModelLR.predict(Tex)

In [35]:
predictLinR

array([ 2.55071670e+05,  1.56671932e+05,  9.80376116e+04,  2.27598979e+05,
        9.76393144e+04,  9.39747268e+04,  2.56847368e+05,  1.45457990e+05,
        5.14480587e+05,  1.47565429e+05,  1.86506441e+05,  1.52729576e+05,
        2.44934386e+05,  1.13751542e+05,  1.37557803e+05,  1.48243169e+05,
        2.36721083e+05,  1.01192491e+05,  1.33466118e+05,  1.79781439e+05,
        1.24086030e+05,  1.49399209e+05,  9.92316228e+04,  1.60191537e+05,
        1.94047155e+05,  1.99859838e+05,  1.49732532e+05,  4.06726568e+04,
        3.12612731e+05,  1.24881144e+05,  1.60295903e+05,  2.15479722e+05,
        1.54242559e+05,  2.86872693e+05,  2.91342791e+05,  2.02068821e+05,
        2.71953367e+05,  1.09934862e+05,  2.32246750e+05,  3.26869321e+05,
        2.15879338e+05,  1.14730181e+05,  1.94071373e+05,  2.92157105e+05,
        3.16544711e+05,  1.29845916e+05,  1.25797623e+05,  1.18456192e+05,
        1.85222382e+05,  8.12667549e+04,  3.66085281e+05,  1.46262217e+05,
        1.92601281e+05,  

In [33]:
#accuracy ca be wrong thus
from sklearn import metrics

In [36]:
metrics.mean_absolute_error(predictLinR, Tey)

21315.384443599516

In [37]:
metrics.r2_score(predictLinR, Tey)

0.7323156117279219

In [38]:
Tey

529     200624
491     133000
459     110000
279     192000
655      88000
         ...  
1001     86000
453     210000
110     136900
1189    189000
1240    224900
Name: SalePrice, Length: 584, dtype: int64

In [39]:
Tex

MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
529           20    32668            6            3       1957          1975   
491           50     9490            6            7       1941          1950   
459           50     7015            5            4       1950          1950   
279           60    10005            7            5       1977          1977   
655          160     1680            6            5       1971          1971   
...          ...      ...          ...          ...        ...           ...   
1001          30     5400            5            6       1920          1950   
453           60     9000            8            5       2008          2008   
110           50     9525            6            4       1954          1972   
1189          60     7500            7            5       1999          1999   
1240          60     8158            7            5       2003          2003   

      BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  1stFlrSF  ...  GarageArea  \
529         1219        816         2035      2515  ...         484   
491          403        238          806       958  ...         240   
459          185        524          709       979  ...         352   
279          392        768         1160      1156  ...         505   
655            0        525          525       525  ...         264   
...          ...        ...          ...       ...  ...         ...   
1001           0        691          691       691  ...         216   
453            0        768          768       786  ...         676   
110          444        550          994      1216  ...         325   
1189           0        994          994      1028  ...         442   
1240         550        334          884       884  ...         543   

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
529            0            0            200          0            0   
491            0            0             32          0            0   
459            0            0            248          0            0   
279          288          117              0          0            0   
655            0            0              0          0            0   
...          ...          ...            ...        ...          ...   
1001           0           20             94          0            0   
453            0           30              0          0            0   
110          182            0              0          0            0   
1189         140           60              0          0            0   
1240           0           63              0          0            0   

      PoolArea  MiscVal  MoSold  YrSold  
529          0        0       3    2007  
491          0        0       8    2006  
459          0        0       7    2009  
279          0        0       3    2008  
655          0        0       3    2010  
...        ...      ...     ...     ...  
1001         0        0       1    2007  
453          0        0       6    2009  
110          0        0      10    2006  
1189         0        0       6    2010  
1240         0        0       7    2008  

[584 rows x 30 columns]

In [40]:
Tx

MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
1169          60    35760           10            5       1995          1996   
1146          20    11200            6            5       1985          1985   
503           20    15602            7            8       1959          1997   
1449         180     1533            5            7       1970          1970   
1063          30     6000            6            6       1925          1980   
...          ...      ...          ...          ...        ...           ...   
763           60     9430            8            5       1999          1999   
835           20     9600            4            7       1950          1995   
1216          90     8930            6            5       1978          1978   
559          120     3196            7            5       2003          2004   
684           60    16770            7            5       1998          1998   

      BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  1stFlrSF  ...  GarageArea  \
1169        1387        543         1930      1831  ...         807   
1146        1258         40         1298      1298  ...         403   
503         1247        254         1501      1801  ...         484   
1449         553         77          630       630  ...           0   
1063         397        706         1103      1103  ...         440   
...          ...        ...          ...       ...  ...         ...   
763         1163         89         1252      1268  ...         856   
835          442        625         1067      1067  ...         436   
1216           0          0            0      1318  ...         539   
559            0       1374         1374      1557  ...         420   
684            0       1195         1195      1195  ...         486   

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
1169         361           76              0          0            0   
1146         165           26              0          0            0   
503            0           54              0          0          161   
1449           0            0              0          0            0   
1063         166          120              0          0            0   
...          ...          ...            ...        ...          ...   
763            0          128              0          0          180   
835          290            0              0          0            0   
1216           0            0              0          0            0   
559          143           20              0          0            0   
684            0           81              0          0            0   

      PoolArea  MiscVal  MoSold  YrSold  
1169         0        0       7    2006  
1146         0        0       5    2006  
503          0        0       3    2010  
1449         0        0       8    2006  
1063         0        0       7    2006  
...        ...      ...     ...     ...  
763          0        0       7    2009  
835          0        0       2    2010  
1216         0        0       4    2010  
559          0        0      10    2006  
684          0        0       6    2010  

[876 rows x 30 columns]

In [41]:
Ty

1169    625000
1146    180000
503     289000
1449     92000
1063    110500
         ...  
763     337000
835     128000
1216    112000
559     234000
684     221000
Name: SalePrice, Length: 876, dtype: int64